linters:
  enable:
    - bodyclose
    - errcheck
    - goconst
    - gofmt
    - gomnd
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unused
    - wsl
    - gosec
